version: '3.8'

services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - mongo
    volumes:
      - ./:/app

  mongo:
    image: docker.arvancloud.ir/mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    env_file:
      - ./.env
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: docker.arvancloud.ir/mongo-express:latest
    container_name: mongo_express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpassword
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongo

volumes:
  mongo-data: